spring:
    application:
        name: sessions-service

server:
    port: ${port:8094}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

security:
  basic:
    enable: false
  ignored: /**

management:
  security:
    enabled: false