tomcat:
 server.tomcat.max-threads: 100

spring:
  application:
    name: eureka-discovery-service

server:
  port: ${port:8761}
  tomcat.max-threads: 100
    
eureka:
  renewalPercentThreshold: 0.85
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    enableSelfPreservation: false
    eviction-interval-timer-in-ms: 1000
    wait-time-in-ms-when-sync-empty: 0