spring:
    application:
        name: questions-service

server:
    port: ${port:8091}
    tomcat:
      accesslog:
        enabled: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetch-registry: true


security:
  basic:
    enable: false
  ignored: /**


management:
  security:
    enabled: false